steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/jchavezar-demo/predictions/prediction:latest', '.' ]
images:
- 'us-central1-docker.pkg.dev/jchavezar-demo/predictions/prediction:latest'